# Generated by Django 3.2.7 on 2021-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_to',
            field=models.DateField(),
        ),
    ]
